### PR TITLE
Bump commonmarker to allow any 0.x version.

### PR DESCRIPTION
**Pull request by parkr**

### CODE REVIEW

**Comment by parkr** [comment]
Hey, we're thinking about adding commonmark support to Pages at some point. Do you think this converter should be added to core, or would you prefer to keep it separate? I could see setting it as the default in Jekyll 4 if a Jekyll 4 ever happens.

**Comment by pathawks** [comment]
Sounds good to me.
I’d be happy to transfer ownership:+1:

**Comment by pathawks** [comment]
> Do you think this converter should be added to core, or would you prefer to keep it separate?

I misunderstood. As far as rolling it into Jekyll Core, that's totally fine with me, but haven't we worked hard to _reduce_ the number of converters included in Core?

**Comment by parkr** [comment]
I think eventually this will replace kramdown. `commonmarker` is much, much
faster than kramdown.

**Comment by pathawks** [comment]
> `commonmarker` is much, much faster than kramdown.

C extensions :+1:

**Pull request merged**
