### PR TITLE
Add Rubocop

### PR DESCRIPTION
**Pull request by DirtyF**
👋  @pathawks,

Thought you might want to follow Jekyll's Ruby StyleGuide for this plugin.

- [x] Add latest rubocop
- [x] Inherit from Jekyll's config
- [x] auto-correct offenses
- [x] list remaining offenses in config

❤️  🤖

### CODE REVIEW

**Comment by pathawks** [comment]
@DirtyF How do you feel about moving this repo to **jekyll/jekyll-commonmark**?

**Comment by DirtyF** [comment]
@pathawks 💚 

👍  I like the idea of Jekyll supporting Commonmark (with a complete test suite). 

As part of the effort at GitHub, @vmg should agree.

**Comment by pathawks** [comment]
I don't have permission to transfer this repo to @jekyll. Looks like only @parkr could do that.

**Comment by pathawks** [comment]
> I like the idea of Jekyll supporting Commonmark (with a complete test suite).

@DirtyF I have transferred the repo to the **jekyll** organization. Let's see if we can get this plugin to a place where more users can start to take advantage of it.

**Pull request merged**
